const ASSESSMENT_THRESHOLDS = Object.freeze({
  APTITUDE_PASS_MARKS: 15,
  TECHNICAL_PASS_MARKS: 15,
  APTITUDE_PASS_PERCENTAGE: 75,
  TECHNICAL_PASS_PERCENTAGE: 75,
  AI_INTERVIEW_PASS_PERCENTAGE: 60,
  FINAL_PASS_PERCENTAGE: 60,
  APTITUDE_WEIGHT: 0.25,
  TECHNICAL_WEIGHT: 0.35,
  AI_INTERVIEW_WEIGHT: 0.4,
  TOTAL_QUESTIONS: 20,
  ASSESSMENT_DURATION_MINUTES: 25,
  PASSING_CORRECT_ANSWERS: 15,
  INTERVIEW_TOTAL_QUESTIONS: 5,
});

const ASSESSMENT_STATUS = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  LOCKED: 'LOCKED',
  IN_PROGRESS: 'IN_PROGRESS',
  APTITUDE: 'APTITUDE',
  APTITUDE_PASSED: 'APTITUDE_PASSED',
  APTITUDE_FAILED: 'APTITUDE_FAILED',
  TECHNICAL: 'TECHNICAL',
  TECHNICAL_PASSED: 'TECHNICAL_PASSED',
  TECHNICAL_FAILED: 'TECHNICAL_FAILED',
  AI_INTERVIEW: 'AI_INTERVIEW',
  AI_INTERVIEW_PASSED: 'AI_INTERVIEW_PASSED',
  AI_INTERVIEW_FAILED: 'AI_INTERVIEW_FAILED',
  TIME_EXPIRED: 'TIME_EXPIRED',
  COMPLETING: 'COMPLETING',
  COMPLETED: 'COMPLETED',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
});

const ASSESSMENT_LEVEL_ORDER = [
  ASSESSMENT_STATUS.NOT_STARTED,
  ASSESSMENT_STATUS.APTITUDE,
  ASSESSMENT_STATUS.APTITUDE_PASSED,
  ASSESSMENT_STATUS.TECHNICAL,
  ASSESSMENT_STATUS.TECHNICAL_PASSED,
  ASSESSMENT_STATUS.AI_INTERVIEW,
  ASSESSMENT_STATUS.AI_INTERVIEW_PASSED,
  ASSESSMENT_STATUS.COMPLETED,
];

module.exports = {
  ASSESSMENT_THRESHOLDS,
  ASSESSMENT_STATUS,
  ASSESSMENT_LEVEL_ORDER,
};
