const { saveTopic } = require('./catalog_helper');

function p(title, slug, topic, diff, stmt, inF, outF, constr, ex, jc, py, cpp, tests, app, tc, sc) {
  return {
    title, slug, topic, difficulty: diff,
    problemStatement: stmt,
    inputFormat: inF || 'Input elements on lines.',
    outputFormat: outF || 'Print output.',
    constraints: constr || ['1 <= N <= 10^5'],
    examples: ex,
    starterCode: { java: jc, python: py, cpp },
    testCases: tests,
    solution: { approach: app || 'Standard stack/queue approach.', timeComplexity: tc || 'O(N)', spaceComplexity: sc || 'O(N)' }
  };
}

// ==========================================
// 1. STACK (10)
// ==========================================
const stack = [
  // 4 Easy
  p('Valid Parentheses', 'stack-valid-parentheses', 'Stack', 'Easy',
    'Given a string s containing just the characters "(", ")", "{", "}", "[" and "]", determine if the input string is valid.',
    'A single line containing string s.', 'Print "true" or "false".', ['1 <= s.length <= 10^4'],
    [{ input: '()', output: 'true', explanation: 'Balanced parentheses.' }, { input: '(]', output: 'false', explanation: 'Mismatched brackets.' }],
    `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.hasNext() ? sc.next() : "";\n        Stack<Character> st = new Stack<>();\n        for (char c : s.toCharArray()) {\n            if (c == '(') st.push(')');\n            else if (c == '{') st.push('}');\n            else if (c == '[') st.push(']');\n            else if (st.isEmpty() || st.pop() != c) { System.out.println("false"); return; }\n        }\n        System.out.println(st.isEmpty() ? "true" : "false");\n    }\n}`,
    `import sys\ndef main():\n    s = sys.stdin.read().strip()\n    st = []\n    m = {'(': ')', '{': '}', '[': ']'}\n    for c in s:\n        if c in m: st.append(m[c])\n        elif not st or st.pop() != c: print("false"); return\n    print("true" if not st else "false")\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <string>\n#include <stack>\nusing namespace std;\nint main() {\n    string s; if (!(cin >> s)) return 0;\n    stack<char> st;\n    for (char c : s) {\n        if (c == '(') st.push(')');\n        else if (c == '{') st.push('}');\n        else if (c == '[') st.push(']');\n        else if (st.empty() || st.top() != c) { cout << "false" << endl; return 0; }\n        else st.pop();\n    }\n    cout << (st.empty() ? "true" : "false") << endl;\n    return 0;\n}`,
    [{ input: '()', expectedOutput: 'true' }, { input: '()[]{}', expectedOutput: 'true' }, { input: '(]', expectedOutput: 'false' }],
    'Push matching expected closing bracket onto stack.', 'O(N)', 'O(N)'),

  p('Min Stack', 'stack-min-stack', 'Stack', 'Easy',
    'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time. Given q operations: 1 x (push x), 2 (pop), 3 (print top), 4 (print min).',
    'First line: q. Next q lines: operation.', 'Print results for queries 3 and 4.', ['1 <= q <= 10^4'],
    [{ input: '6\n1 -2\n1 0\n1 -3\n4\n2\n3', output: '-3\n0', explanation: 'Min is -3. After pop, top is 0.' }],
    `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int q = sc.nextInt();\n        Stack<Integer> st = new Stack<>(), minSt = new Stack<>();\n        while (q-- > 0) {\n            int t = sc.nextInt();\n            if (t == 1) {\n                int x = sc.nextInt(); st.push(x);\n                minSt.push(minSt.isEmpty() || x <= minSt.peek() ? x : minSt.peek());\n            } else if (t == 2) {\n                st.pop(); minSt.pop();\n            } else if (t == 3) System.out.println(st.peek());\n            else System.out.println(minSt.peek());\n        }\n    }\n}`,
    `import sys\ndef main():\n    d = sys.stdin.read().split()\n    if not d: return\n    q = int(d[0]); idx = 1; st = []; min_st = []\n    for _ in range(q):\n        t = int(d[idx]); idx += 1\n        if t == 1:\n            x = int(d[idx]); idx += 1; st.append(x)\n            min_st.append(x if not min_st or x <= min_st[-1] else min_st[-1])\n        elif t == 2: st.pop(); min_st.pop()\n        elif t == 3: print(st[-1])\n        else: print(min_st[-1])\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <stack>\nusing namespace std;\nint main() {\n    int q; if (!(cin >> q)) return 0;\n    stack<int> st, minSt;\n    while (q--) {\n        int t; cin >> t;\n        if (t == 1) {\n            int x; cin >> x; st.push(x);\n            minSt.push(minSt.empty() || x <= minSt.top() ? x : minSt.top());\n        } else if (t == 2) { st.pop(); minSt.pop(); }\n        else if (t == 3) cout << st.top() << endl;\n        else cout << minSt.top() << endl;\n    }\n    return 0;\n}`,
    [{ input: '6\n1 -2\n1 0\n1 -3\n4\n2\n3', expectedOutput: '-3\n0' }],
    'Two parallel stacks tracking running minimum.', 'O(1) per op', 'O(N)'),

  p('Implement Queue using Stacks', 'stack-implement-queue-using-stacks', 'Stack', 'Easy',
    'Implement a first in first out (FIFO) queue using only two stacks. Operations: 1 x (push x), 2 (pop and print removed element), 3 (print front).',
    'First line: q. Next q lines: operation.', 'Print results for ops 2 and 3.', ['1 <= q <= 1000'],
    [{ input: '4\n1 1\n1 2\n3\n2', output: '1\n1', explanation: 'Front is 1, popped is 1.' }],
    `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int q = sc.nextInt();\n        Stack<Integer> in = new Stack<>(), out = new Stack<>();\n        while (q-- > 0) {\n            int t = sc.nextInt();\n            if (t == 1) in.push(sc.nextInt());\n            else {\n                if (out.isEmpty()) while (!in.isEmpty()) out.push(in.pop());\n                if (t == 2) System.out.println(out.pop());\n                else System.out.println(out.peek());\n            }\n        }\n    }\n}`,
    `import sys\ndef main():\n    d = sys.stdin.read().split()\n    if not d: return\n    q = int(d[0]); idx = 1; in_st = []; out_st = []\n    for _ in range(q):\n        t = int(d[idx]); idx += 1\n        if t == 1: in_st.append(int(d[idx])); idx += 1\n        else:\n            if not out_st:\n                while in_st: out_st.append(in_st.pop())\n            print(out_st.pop() if t == 2 else out_st[-1])\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <stack>\nusing namespace std;\nint main() {\n    int q; if (!(cin >> q)) return 0;\n    stack<int> in, out;\n    while (q--) {\n        int t; cin >> t;\n        if (t == 1) { int x; cin >> x; in.push(x); }\n        else {\n            if (out.empty()) while (!in.empty()) { out.push(in.top()); in.pop(); }\n            if (t == 2) { cout << out.top() << endl; out.pop(); } else cout << out.top() << endl;\n        }\n    }\n    return 0;\n}`,
    [{ input: '4\n1 1\n1 2\n3\n2', expectedOutput: '1\n1' }],
    'Amortized O(1) two stacks queue.', 'O(1) amortized', 'O(N)'),

  p('Remove All Adjacent Duplicates In String', 'stack-remove-all-adjacent-duplicates', 'Stack', 'Easy',
    'Given a string s consisting of lowercase English letters, a duplicate removal consists of choosing two adjacent and equal letters and removing them. Repeat until no more duplicates remain.',
    'A single string s.', 'Print final string.', ['1 <= s.length <= 10^5'],
    [{ input: 'abbaca', output: 'ca', explanation: '"bb" removed -> "aaca" -> "aa" removed -> "ca".' }],
    `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.hasNext() ? sc.next() : "";\n        StringBuilder sb = new StringBuilder();\n        for (char c : s.toCharArray()) {\n            int len = sb.length();\n            if (len > 0 && sb.charAt(len - 1) == c) sb.deleteCharAt(len - 1);\n            else sb.append(c);\n        }\n        System.out.println(sb.toString());\n    }\n}`,
    `import sys\ndef main():\n    s = sys.stdin.read().strip()\n    st = []\n    for c in s:\n        if st and st[-1] == c: st.pop()\n        else: st.append(c)\n    print("".join(st))\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s; if (!(cin >> s)) return 0;\n    string res = "";\n    for (char c : s) {\n        if (!res.empty() && res.back() == c) res.pop_back();\n        else res.push_back(c);\n    }\n    cout << res << endl;\n    return 0;\n}`,
    [{ input: 'abbaca', expectedOutput: 'ca' }, { input: 'azxxzy', expectedOutput: 'ay' }],
    'Stack or StringBuilder acting as stack.', 'O(N)', 'O(N)'),

  // 3 Medium
  p('Daily Temperatures', 'stack-daily-temperatures', 'Stack', 'Medium',
    'Given an array of integers temperatures represents the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the ith day to get a warmer temperature.',
    'First line: n. Second line: n temperatures.', 'Print wait days separated by spaces.', ['1 <= temperatures.length <= 10^5'],
    [{ input: '8\n73 74 75 71 69 72 76 73', output: '1 1 4 2 1 1 0 0', explanation: 'Days to wait for warmer temp.' }],
    `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] t = new int[n], ans = new int[n];\n        for (int i = 0; i < n; i++) t[i] = sc.nextInt();\n        Stack<Integer> st = new Stack<>();\n        for (int i = 0; i < n; i++) {\n            while (!st.isEmpty() && t[i] > t[st.peek()]) {\n                int prev = st.pop(); ans[prev] = i - prev;\n            }\n            st.push(i);\n        }\n        for (int i = 0; i < n; i++) System.out.print(ans[i] + (i == n - 1 ? "" : " "));\n        System.out.println();\n    }\n}`,
    `import sys\ndef main():\n    d = sys.stdin.read().split()\n    if not d: return\n    n = int(d[0]); t = [int(x) for x in d[1:n+1]]\n    ans = [0] * n; st = []\n    for i, x in enumerate(t):\n        while st and x > t[st[-1]]:\n            prev = st.pop(); ans[prev] = i - prev\n        st.append(i)\n    print(" ".join(str(x) for x in ans))\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <vector>\n#include <stack>\nusing namespace std;\nint main() {\n    int n; if (!(cin >> n)) return 0;\n    vector<int> t(n), ans(n, 0); for (int i = 0; i < n; i++) cin >> t[i];\n    stack<int> st;\n    for (int i = 0; i < n; i++) {\n        while (!st.empty() && t[i] > t[st.top()]) {\n            int prev = st.top(); st.pop(); ans[prev] = i - prev;\n        }\n        st.push(i);\n    }\n    for (int i = 0; i < n; i++) cout << ans[i] << (i == n - 1 ? "" : " ");\n    cout << endl;\n    return 0;\n}`,
    [{ input: '8\n73 74 75 71 69 72 76 73', expectedOutput: '1 1 4 2 1 1 0 0' }],
    'Monotonic decreasing stack of indices.', 'O(N)', 'O(N)'),

  p('Evaluate Reverse Polish Notation', 'stack-evaluate-reverse-polish-notation', 'Stack', 'Medium',
    'Evaluate the value of an arithmetic expression in Reverse Polish Notation. Valid operators are +, -, *, and /. Division truncates toward zero.',
    'First line: n. Second line: n tokens separated by space.', 'Print integer result.', ['1 <= tokens.length <= 10^4'],
    [{ input: '5\n2 1 + 3 *', output: '9', explanation: '((2 + 1) * 3) = 9.' }, { input: '5\n4 13 5 / +', output: '6', explanation: '(4 + (13 / 5)) = 6.' }],
    `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Stack<Integer> st = new Stack<>();\n        for (int i = 0; i < n; i++) {\n            String s = sc.next();\n            if (s.equals("+")) st.push(st.pop() + st.pop());\n            else if (s.equals("-")) { int b = st.pop(), a = st.pop(); st.push(a - b); }\n            else if (s.equals("*")) st.push(st.pop() * st.pop());\n            else if (s.equals("/")) { int b = st.pop(), a = st.pop(); st.push(a / b); }\n            else st.push(Integer.parseInt(s));\n        }\n        System.out.println(st.peek());\n    }\n}`,
    `import sys\ndef main():\n    d = sys.stdin.read().split()\n    if not d: return\n    n = int(d[0]); tokens = d[1:n+1]; st = []\n    for t in tokens:\n        if t == '+': st.append(st.pop() + st.pop())\n        elif t == '-': b, a = st.pop(), st.pop(); st.append(a - b)\n        elif t == '*': st.append(st.pop() * st.pop())\n        elif t == '/': b, a = st.pop(), st.pop(); st.append(int(a / b))\n        else: st.append(int(t))\n    print(st[-1])\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <string>\n#include <stack>\nusing namespace std;\nint main() {\n    int n; if (!(cin >> n)) return 0;\n    stack<int> st;\n    for (int i = 0; i < n; i++) {\n        string s; cin >> s;\n        if (s == "+") { int b = st.top(); st.pop(); int a = st.top(); st.pop(); st.push(a + b); }\n        else if (s == "-") { int b = st.top(); st.pop(); int a = st.top(); st.pop(); st.push(a - b); }\n        else if (s == "*") { int b = st.top(); st.pop(); int a = st.top(); st.pop(); st.push(a * b); }\n        else if (s == "/") { int b = st.top(); st.pop(); int a = st.top(); st.pop(); st.push(a / b); }\n        else st.push(stoi(s));\n    }\n    cout << st.top() << endl;\n    return 0;\n}`,
    [{ input: '5\n2 1 + 3 *', expectedOutput: '9' }, { input: '5\n4 13 5 / +', expectedOutput: '6' }],
    'Stack operand evaluation.', 'O(N)', 'O(N)'),

  p('Next Greater Element II', 'stack-next-greater-element-ii', 'Stack', 'Medium',
    'Given a circular integer array nums, return the next greater number for every element. If it doesn\'t exist, return -1.',
    'First line: n. Second line: n integers.', 'Print next greater elements separated by space.', ['1 <= nums.length <= 10^4'],
    [{ input: '3\n1 2 1', output: '2 -1 2', explanation: 'Next greater for circular array.' }],
    `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n], ans = new int[n];\n        Arrays.fill(ans, -1);\n        for (int i = 0; i < n; i++) a[i] = sc.nextInt();\n        Stack<Integer> st = new Stack<>();\n        for (int i = 0; i < 2 * n; i++) {\n            int val = a[i % n];\n            while (!st.isEmpty() && a[st.peek()] < val) ans[st.pop()] = val;\n            if (i < n) st.push(i);\n        }\n        for (int i = 0; i < n; i++) System.out.print(ans[i] + (i == n - 1 ? "" : " "));\n        System.out.println();\n    }\n}`,
    `import sys\ndef main():\n    d = sys.stdin.read().split()\n    if not d: return\n    n = int(d[0]); a = [int(x) for x in d[1:n+1]]\n    ans = [-1] * n; st = []\n    for i in range(2 * n):\n        val = a[i % n]\n        while st and a[st[-1]] < val: ans[st.pop()] = val\n        if i < n: st.append(i)\n    print(" ".join(str(x) for x in ans))\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <vector>\n#include <stack>\nusing namespace std;\nint main() {\n    int n; if (!(cin >> n)) return 0;\n    vector<int> a(n), ans(n, -1); for (int i = 0; i < n; i++) cin >> a[i];\n    stack<int> st;\n    for (int i = 0; i < 2 * n; i++) {\n        int val = a[i % n];\n        while (!st.empty() && a[st.top()] < val) { ans[st.top()] = val; st.pop(); }\n        if (i < n) st.push(i);\n    }\n    for (int i = 0; i < n; i++) cout << ans[i] << (i == n - 1 ? "" : " ");\n    cout << endl;\n    return 0;\n}`,
    [{ input: '3\n1 2 1', expectedOutput: '2 -1 2' }],
    'Double-pass circular array with monotonic stack.', 'O(N)', 'O(N)'),

  // 3 Hard
  p('Basic Calculator', 'stack-basic-calculator', 'Stack', 'Hard',
    'Given a string s representing a valid expression, evaluate this expression and return its value. The expression may contain \'+\', \'-\', \'(\', \')\', and non-negative integers.',
    'A single line containing the expression string.', 'Print integer result.', ['1 <= s.length <= 10^5'],
    [{ input: '1 + 1', output: '2', explanation: 'Simple addition.' }, { input: ' 2-1 + 2 ', output: '3', explanation: 'Result is 3.' }, { input: '(1+(4+5+2)-3)+(6+8)', output: '23', explanation: 'Parenthesized expression.' }],
    `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.hasNextLine() ? sc.nextLine() : "";\n        Stack<Integer> st = new Stack<>();\n        int sign = 1, res = 0, num = 0;\n        for (int i = 0; i < s.length(); i++) {\n            char c = s.charAt(i);\n            if (Character.isDigit(c)) num = num * 10 + (c - '0');\n            else if (c == '+') { res += sign * num; num = 0; sign = 1; }\n            else if (c == '-') { res += sign * num; num = 0; sign = -1; }\n            else if (c == '(') { st.push(res); st.push(sign); res = 0; sign = 1; }\n            else if (c == ')') { res += sign * num; num = 0; res *= st.pop(); res += st.pop(); }\n        }\n        res += sign * num;\n        System.out.println(res);\n    }\n}`,
    `import sys\ndef main():\n    s = sys.stdin.readline().strip()\n    st = []; res = num = 0; sign = 1\n    for c in s:\n        if c.isdigit(): num = num * 10 + int(c)\n        elif c == '+': res += sign * num; num = 0; sign = 1\n        elif c == '-': res += sign * num; num = 0; sign = -1\n        elif c == '(': st.append(res); st.append(sign); res = 0; sign = 1\n        elif c == ')': res += sign * num; num = 0; res *= st.pop(); res += st.pop()\n    res += sign * num\n    print(res)\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <string>\n#include <stack>\nusing namespace std;\nint main() {\n    string s; if (!getline(cin, s)) return 0;\n    stack<int> st; int sign = 1, res = 0, num = 0;\n    for (char c : s) {\n        if (isdigit(c)) num = num * 10 + (c - '0');\n        else if (c == '+') { res += sign * num; num = 0; sign = 1; }\n        else if (c == '-') { res += sign * num; num = 0; sign = -1; }\n        else if (c == '(') { st.push(res); st.push(sign); res = 0; sign = 1; }\n        else if (c == ')') { res += sign * num; num = 0; res *= st.top(); st.pop(); res += st.top(); st.pop(); }\n    }\n    res += sign * num;\n    cout << res << endl;\n    return 0;\n}`,
    [{ input: '1 + 1', expectedOutput: '2' }, { input: '(1+(4+5+2)-3)+(6+8)', expectedOutput: '23' }],
    'Stack for signs and partial results at parenthesis depths.', 'O(N)', 'O(N)'),

  p('Maximal Rectangle', 'stack-maximal-rectangle', 'Stack', 'Hard',
    'Given a rows x cols binary matrix filled with 0s and 1s, find the largest rectangle containing only 1s and return its area.',
    'First line: r and c. Next r lines contain c space-separated values (0 or 1).', 'Print maximum area.', ['1 <= r, c <= 200'],
    [{ input: '4 5\n1 0 1 0 0\n1 0 1 1 1\n1 1 1 1 1\n1 0 0 1 0', output: '6', explanation: 'Maximal rectangle has area 6.' }],
    `import java.util.*;\npublic class Main {\n    private static int largestHist(int[] h) {\n        Stack<Integer> st = new Stack<>();\n        int maxA = 0, n = h.length;\n        for (int i = 0; i <= n; i++) {\n            int cur = (i == n) ? 0 : h[i];\n            while (!st.isEmpty() && cur < h[st.peek()]) {\n                int height = h[st.pop()];\n                int width = st.isEmpty() ? i : i - st.peek() - 1;\n                maxA = Math.max(maxA, height * width);\n            }\n            st.push(i);\n        }\n        return maxA;\n    }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int r = sc.nextInt(), c = sc.nextInt();\n        int[] h = new int[c];\n        int maxArea = 0;\n        for (int i = 0; i < r; i++) {\n            for (int j = 0; j < c; j++) {\n                int v = sc.nextInt(); h[j] = (v == 1) ? h[j] + 1 : 0;\n            }\n            maxArea = Math.max(maxArea, largestHist(h));\n        }\n        System.out.println(maxArea);\n    }\n}`,
    `import sys\ndef main():\n    d = sys.stdin.read().split()\n    if not d: return\n    r, c = int(d[0]), int(d[1])\n    h = [0] * c; max_a = 0; idx = 2\n    for _ in range(r):\n        for j in range(c):\n            v = int(d[idx]); idx += 1\n            h[j] = h[j] + 1 if v == 1 else 0\n        st = []; n = c\n        for i in range(n + 1):\n            cur = 0 if i == n else h[i]\n            while st and cur < h[st[-1]]:\n                ht = h[st.pop()]\n                w = i if not st else i - st[-1] - 1\n                max_a = max(max_a, ht * w)\n            st.append(i)\n    print(max_a)\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <vector>\n#include <stack>\nusing namespace std;\nint hist(const vector<int>& h) {\n    stack<int> st; int maxA = 0, n = h.size();\n    for (int i = 0; i <= n; i++) {\n        int cur = (i == n) ? 0 : h[i];\n        while (!st.empty() && cur < h[st.top()]) {\n            int ht = h[st.top()]; st.pop();\n            int w = st.empty() ? i : i - st.top() - 1;\n            maxA = max(maxA, ht * w);\n        }\n        st.push(i);\n    }\n    return maxA;\n}\nint main() {\n    int r, c; if (!(cin >> r >> c)) return 0;\n    vector<int> h(c, 0); int maxA = 0;\n    for (int i = 0; i < r; i++) {\n        for (int j = 0; j < c; j++) { int v; cin >> v; h[j] = (v == 1) ? h[j] + 1 : 0; }\n        maxA = max(maxA, hist(h));\n    }\n    cout << maxA << endl;\n    return 0;\n}`,
    [{ input: '4 5\n1 0 1 0 0\n1 0 1 1 1\n1 1 1 1 1\n1 0 0 1 0', expectedOutput: '6' }],
    'Row by row histogram accumulation with monotonic stack.', 'O(R * C)', 'O(C)'),

  p('Trapping Rain Water II', 'stack-trapping-rain-water-ii', 'Stack', 'Hard',
    'Given an m x n integer matrix heights representing the height of each unit cell in a 2D elevation map, return the volume of water it can trap after raining.',
    'First line: m and n. Next m lines: n integers.', 'Print trapped water volume.', ['1 <= m, n <= 100'],
    [{ input: '3 6\n1 4 3 1 3 2\n3 2 1 3 2 4\n2 3 3 2 3 1', output: '4', explanation: 'Volume trapped is 4.' }],
    `import java.util.*;\npublic class Main {\n    static class Cell implements Comparable<Cell> {\n        int r, c, h;\n        Cell(int r, int c, int h) { this.r = r; this.c = c; this.h = h; }\n        public int compareTo(Cell o) { return Integer.compare(this.h, o.h); }\n    }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int m = sc.nextInt(), n = sc.nextInt();\n        int[][] grid = new int[m][n];\n        for (int i = 0; i < m; i++) for (int j = 0; j < n; j++) grid[i][j] = sc.nextInt();\n        PriorityQueue<Cell> pq = new PriorityQueue<>();\n        boolean[][] vis = new boolean[m][n];\n        for (int i = 0; i < m; i++) {\n            pq.offer(new Cell(i, 0, grid[i][0])); vis[i][0] = true;\n            pq.offer(new Cell(i, n - 1, grid[i][n - 1])); vis[i][n - 1] = true;\n        }\n        for (int j = 0; j < n; j++) {\n            if (!vis[0][j]) { pq.offer(new Cell(0, j, grid[0][j])); vis[0][j] = true; }\n            if (!vis[m - 1][j]) { pq.offer(new Cell(m - 1, j, grid[m - 1][j])); vis[m - 1][j] = true; }\n        }\n        int water = 0;\n        int[][] dirs = {{1,0},{-1,0},{0,1},{0,-1}};\n        while (!pq.isEmpty()) {\n            Cell cur = pq.poll();\n            for (int[] d : dirs) {\n                int nr = cur.r + d[0], nc = cur.c + d[1];\n                if (nr >= 0 && nr < m && nc >= 0 && nc < n && !vis[nr][nc]) {\n                    vis[nr][nc] = true;\n                    water += Math.max(0, cur.h - grid[nr][nc]);\n                    pq.offer(new Cell(nr, nc, Math.max(cur.h, grid[nr][nc])));\n                }\n            }\n        }\n        System.out.println(water);\n    }\n}`,
    `import sys, heapq\ndef main():\n    d = sys.stdin.read().split()\n    if not d: return\n    m, n = int(d[0]), int(d[1])\n    grid = []; idx = 2\n    for _ in range(m): grid.append([int(x) for x in d[idx:idx+n]]); idx += n\n    pq = []; vis = [[False]*n for _ in range(m)]\n    for i in range(m):\n        for j in (0, n - 1):\n            heapq.heappush(pq, (grid[i][j], i, j)); vis[i][j] = True\n    for j in range(n):\n        for i in (0, m - 1):\n            if not vis[i][j]: heapq.heappush(pq, (grid[i][j], i, j)); vis[i][j] = True\n    water = 0\n    while pq:\n        h, r, c = heapq.heappop(pq)\n        for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):\n            nr, nc = r + dr, c + dc\n            if 0 <= nr < m and 0 <= nc < n and not vis[nr][nc]:\n                vis[nr][nc] = True\n                water += max(0, h - grid[nr][nc])\n                heapq.heappush(pq, (max(h, grid[nr][nc]), nr, nc))\n    print(water)\nif __name__ == '__main__': main()`,
    `#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\nstruct Cell { int r, c, h; bool operator>(const Cell& o) const { return h > o.h; } };\nint main() {\n    int m, n; if (!(cin >> m >> n)) return 0;\n    vector<vector<int>> g(m, vector<int>(n));\n    for (int i = 0; i < m; i++) for (int j = 0; j < n; j++) cin >> g[i][j];\n    priority_queue<Cell, vector<Cell>, greater<Cell>> pq;\n    vector<vector<bool>> vis(m, vector<bool>(n, false));\n    for (int i = 0; i < m; i++) {\n        pq.push({i, 0, g[i][0]}); vis[i][0] = true;\n        pq.push({i, n - 1, g[i][n - 1]}); vis[i][n - 1] = true;\n    }\n    for (int j = 0; j < n; j++) {\n        if (!vis[0][j]) { pq.push({0, j, g[0][j]}); vis[0][j] = true; }\n        if (!vis[m - 1][j]) { pq.push({m - 1, j, g[m - 1][j]}); vis[m - 1][j] = true; }\n    }\n    int water = 0; int dr[] = {1, -1, 0, 0}, dc[] = {0, 0, 1, -1};\n    while (!pq.empty()) {\n        Cell cur = pq.top(); pq.pop();\n        for (int d = 0; d < 4; d++) {\n            int nr = cur.r + dr[d], nc = cur.c + dc[d];\n            if (nr >= 0 && nr < m && nc >= 0 && nc < n && !vis[nr][nc]) {\n                vis[nr][nc] = true;\n                water += max(0, cur.h - g[nr][nc]);\n                pq.push({nr, nc, max(cur.h, g[nr][nc])});\n            }\n        }\n    }\n    cout << water << endl;\n    return 0;\n}`,
    [{ input: '3 6\n1 4 3 1 3 2\n3 2 1 3 2 4\n2 3 3 2 3 1', expectedOutput: '4' }],
    'PriorityQueue min-heap boundary BFS.', 'O(M * N log(M * N))', 'O(M * N)')
];

saveTopic('stack.js', stack);
